services:
  pgdatabase:
    image: postgres:13
    #container_name: pg-database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data"

  pgadmin:
    image: dpage/pgadmin4
    #container_name: pgadmin
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: fensalsdx@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    